import os
import sys
#import shutils

lib_path = ['.']
libs = []
includes = []
      
if sys.platform == 'darwin':
      boost_lib_path = [os.path.join('boost', 'macosx-x86-64', 'lib')]
      boost_includes = [os.path.join('boost', 'macosx-x86-64', 'include')]
      boost_libs = ['libboost_prg_exec_monitor.a', 'libboost_python.a', 'libboost_system.a', 
            'libboost_test_exec_monitor.a', 'libboost_thread.a', 
            'libboost_unit_test_framework.a']
      python_includes = ['/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/']
      libname = 'libboosted_bci_darwin_x86_64'
else:
      boost_lib_path = []
      boost_includes = []
      boost_libs = []

lib_path.extend(boost_lib_path)
libs.extend(boost_libs)
includes.extend(boost_includes)
includes.extend(python_includes)
frameworks = ["Python"]

env = Environment(CPPPATH = includes, LIBS = libs, LIBPATH = lib_path,
                  FRAMEWORKS = frameworks, SHLIBPREFIX = '',
                  SHLIBSUFFIX = '.so')

SOURCES=['boosted_bci.cpp', 'NonblockingBci.cpp', 'FakeBci.cpp', 'AsyncSampleCollector.cpp', 'ManagedWorkController.cpp']
boost_bci = env.SharedLibrary(libname, SOURCES)

unit_test_libs=['libboost_unit_test_framework.a']
UNIT_TEST_SOURCES=['AsyncSampleCollectorTest.cpp', 'BciTestRunner.cpp', 'NonblockingBciTest.cpp',
                   'SampleTest.cpp' ]
libs.append(libname)

test_env = Environment(CPPPATH = includes, LIBS = libs, LIBPATH = lib_path)
test_boost_bci = test_env.Program('bci-unit-tests', UNIT_TEST_SOURCES)
test_env.Requires(test_boost_bci, boost_bci)
