import os
import sys

lib_path = ['.']
libs = []
includes = []
      
if sys.platform == 'darwin':
      boost_lib_path = [os.path.join('boost', 'macosx-x86-64', 'lib')]
      boost_includes = [os.path.join('boost', 'macosx-x86-64', 'include')]
      boost_libs = ['libboost_prg_exec_monitor.a', 'libboost_python.a', 'libboost_system.a', 
            'libboost_test_exec_monitor.a', 'libboost_thread.a', 
            'libboost_unit_test_framework.a']
      python_includes = ['/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/']
      libname = 'boosted_bci_darwin_x86_64'
else:
      boost_lib_path = []
      boost_includes = []
      boost_libs = []

lib_path.extend(boost_lib_path)
libs.extend(boost_libs)
includes.extend(boost_includes)
includes.extend(python_includes)
frameworks = ["Python"]

env = Environment(CPPPATH = includes, LIBS = libs, LIBPATH = lib_path,
                  FRAMEWORKS = frameworks, SHLIBPREFIX = '',
                  SHLIBSUFFIX = '.so')

SOURCES=['boosted_bci.cc', 'nonblocking_bci.cc', 'fake_bci.cc']
env.SharedLibrary(libname, SOURCES)

