import os
import sys

env = Environment()

#sources = env.Glob("*.cc")
#print sources

#env.Append(CPPPATH = [os.path.join(boost_prefix, "include")])
#env.Append(LIBPATH = [os.path.join(boost_prefix, "lib")]
#Program(target = "test", source = sources, LIBS = [])
#env.Default(app)
#env.Append(CPPPATH = ["boost_1_54_0"])
#obj = Object("enobio.cc")
lib_path = []
libs = []
includes = []
      
if sys.platform == 'darwin':
      boost_lib_path = [os.path.join('boost', 'macosx-x86-64', 'lib')]
      boost_includes = [os.path.join('boost', 'macosx-x86-64', 'include')]
      boost_libs = ['libboost_prg_exec_monitor.a', 'libboost_python.a', 'libboost_system.a', 
            'libboost_test_exec_monitor.a', 'libboost_thread.a', 
            'libboost_unit_test_framework.a']
else:
      boost_lib_path = []
      boost_includes = []
      boost_libs = []

lib_path.extend(boost_lib_path)
libs.extend(boost_libs)
includes.extend(boost_includes)

SharedLibrary('enobio', ['enobio.cc'], LIBPATH=lib_path, CPPPATH=includes, LIBS=libs)
#Program('enobio-main', 'enobio-main.cc', LIBS='enobio', CPPPATH=includes)
